### ISSUE TITLE
Реализовать поддержку альбомов для фото

### ISSUE THREAD

**Issue by kszakharov** [DvaMishkiLapa/VKArchiveDownloader#17]
Просьба рассмотреть возможность реализации поддержки альбомов (папок) для фото

**Comment by DvaMishkiLapa** [comment]
Посмотрю, что с этим можно сделать.

**Comment by DvaMishkiLapa** [comment]
Кажется, оно уже должно работать, так как входит в фото самого профиля.
Мне нечем проверить, не имею у себя никаких альбомов. Может, у вас получиться.

Речь идет о `.\Archive\photos\*`
Результат должен быть тут: `.\output\photos\image\jpeg`

Если оно все же не работает - дайте мне знать.

**Comment by kszakharov** [comment]
Фото из всех альбомов сохраняется в `.\output\photos\image\jpeg`

**Comment by DvaMishkiLapa** [comment]
Хочется разделения на папки, таких же, как у альбомов?

**Comment by kszakharov** [comment]
Да :)

**Comment by DvaMishkiLapa** [comment]
Кажется, теперь это работает.

Все альбомы, которые будут найдены `.\Archive\photos\photo-albums\*`, будут скачаны в отдельные папки по пути:
`.\photos\photo-albums\*`. Имена папок - имена альбомов.

Если это работает и у вас - можете закрыть запрос :)

**Comment by kszakharov** [comment]
Отлично работает, спасибо!
