### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by SergeySemirenko** [DvaMishkiLapa/VKArchiveDownloader#28]
<img width="1280" alt="Снимок экрана 2024-02-22 023850" src="https://github.com/DvaMishkiLapa/VKArchiveDownloader/assets/160782303/adba4936-795e-4ef3-acf2-9a886d9d4dc3">

Добрый день!
Прошу о помощи. При запуске утилиты возникают следующие ошибки. В результате папки, в которых должны быть файлы, пусты
Я человек совершенно далёкий от Python, потому прошу о снисхождении и учете этого при ответе
Спасибо!

**Comment by DvaMishkiLapa** [comment]
Добрый день, @SergeySemirenko!

После работы приложения в папке с ним должен лежать log-файл `*.log`. Можете скинуть его мне, сюда?

**Comment by SergeySemirenko** [comment]
[vk_parser.log](https://github.com/DvaMishkiLapa/VKArchiveDownloader/files/14395759/vk_parser.log)

**Comment by DvaMishkiLapa** [comment]
Какая версия ОС у вас установлена?

Как возможные варианты решения:
Внутри `.venv` (описано в README, о чем речь), выполнить
```sh
pip3 install pip_system_certs
```

Пока что я теряюсь в догадках, что у вас не так. Вы можете через браузер зайти в VK? С этим есть проблемы?

**Comment by SergeySemirenko** [comment]
Windows 11 Pro 23H2, лицензия

Нет, проблем со входом в VK через браузер нет
При этом в config.ini. выставлено значение use_coockie=False, поскольку мне необходимо извлечь только те файлы, которые имеются в самом архиве

**Comment by DvaMishkiLapa** [comment]
@SergeySemirenko
Если это для вас еще актуально, было выпущено обновление, где проверку [SSL можно отключить, если нет других альтернатив](https://github.com/DvaMishkiLapa/VKArchiveDownloader/releases/tag/3.0.1).
